id: P007851
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25192
  title: རིམ་ལྔའི་མཐའ་དཔྱོད་གསང་དོན་ཀུནྡ་བཞད་པའི་ལེགས་བཤད་རྒྱུ་སྐར་བདག་པོ།
  author: ''
  volumes:
    6c7970166091475d9994d76d988b4094:
      image_group_id: I1KG25194
      title: ''
      volume_number: 1
      total_pages: 280
ebook_metadata:
  title: རིམ་ལྔའི་མཐའ་དཔྱོད་གསང་དོན་ཀུནྡ་བཞད་པའི་ལེགས་བཤད་རྒྱུ་སྐར་བདག་པོ།
  author: ''
  sku: P007851
  cover: cover.jpg
  layers:
  - pagination
