id: P007851
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG25192
  title: རིམ་ལྔའི་མཐའ་དཔྱོད་གསང་དོན་ཀུནྡ་བཞད་པའི་ལེགས་བཤད་རྒྱུ་སྐར་བདག་པོ།
  author: ''
  volumes:
    4a498f3c42424799bbfe38ca9f07a4d4:
      image_group_id: I1KG25194
      title: Volume 1 of rim lnga'i mtha' dpyod gsang don kun+da bzhad pa'i legs bshad
        rgyu skar bdag po/
      volume_number: 1
      total_pages: 280
      base_file: v001.txt
