id: I3B9842C2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:56:02+00:00'
last_modified: '2022-06-09T06:35:35.544347+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25192
  title: རིམ་ལྔའི་མཐའ་དཔྱོད་གསང་དོན་ཀུནྡ་བཞད་པའི་ལེགས་བཤད་རྒྱུ་སྐར་བདག་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    93A4:
      image_group_id: I1KG25194
      title: Volume 1 of rim lnga'i mtha' dpyod gsang don kun+da bzhad pa'i legs bshad
        rgyu skar bdag po/
      total_pages: 280
      order: 1
      base_file: 93A4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
